#!/bin/sh
reg_name='kind-registry'
reg_port='5000'

# create registry container unless it already exists

running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"
if [ "${running}" != 'true' ]; then
  docker run \
    -d --restart=always -p "${reg_port}:5000" --name "${reg_name}" \
    registry:2
fi

# connect the registry to the cluster network
# (the network may already be connected)

docker network connect "kind" "${reg_name}" > /dev/null 2>&1 &
